run:
  deadline: 5m

output:
  format: colored-line-number

issues:
  exclude-use-default: false
  exclude:
    - "exported \\w+ (\\S*['.]*)([a-zA-Z'.*]*) should have comment( \\(or a comment on this block\\))? or be unexported"
    - "Error return value of .((os\\.)?std(out|err)\\..*|.*Close|.*Flush|os\\.Remove(All)?|.*printf?|os\\.(Un)?Setenv). is not checked"
    - "package-comments: should have a package comment"
    - "unused-parameter: parameter '\\w+' seems to be unused, consider removing or renaming it as _"

linters:
  enable:
    - errcheck
    - revive
    - goimports
    - govet
    - misspell
    - staticcheck
    - unused
    - unparam
