// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package core

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/golang/protobuf/ptypes/any"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AuthRequest_ResponseType int32

const (
	AuthRequest_UNKNOWN AuthRequest_ResponseType = 0
	AuthRequest_CODE    AuthRequest_ResponseType = 1
	AuthRequest_TOKEN   AuthRequest_ResponseType = 2
)

var AuthRequest_ResponseType_name = map[int32]string{
	0: "UNKNOWN",
	1: "CODE",
	2: "TOKEN",
}

var AuthRequest_ResponseType_value = map[string]int32{
	"UNKNOWN": 0,
	"CODE":    1,
	"TOKEN":   2,
}

func (x AuthRequest_ResponseType) String() string {
	return proto.EnumName(AuthRequest_ResponseType_name, int32(x))
}

func (AuthRequest_ResponseType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0, 0}
}

type Session_Stage int32

const (
	// A request to authenticate someone has been received, but upstream has not
	// authenticated the user.
	Session_REQUESTED Session_Stage = 0
	// Code flow was requested, and a code has been issued.
	Session_CODE Session_Stage = 1
	// An access token has been issued to the user, but the session is not for
	// offline access (aka no refresh token)
	Session_ACCESS_TOKEN_ISSUED Session_Stage = 2
	// An access token has been issued, along with a refresh token.
	Session_REFRESHABLE Session_Stage = 3
)

var Session_Stage_name = map[int32]string{
	0: "REQUESTED",
	1: "CODE",
	2: "ACCESS_TOKEN_ISSUED",
	3: "REFRESHABLE",
}

var Session_Stage_value = map[string]int32{
	"REQUESTED":           0,
	"CODE":                1,
	"ACCESS_TOKEN_ISSUED": 2,
	"REFRESHABLE":         3,
}

func (x Session_Stage) String() string {
	return proto.EnumName(Session_Stage_name, int32(x))
}

func (Session_Stage) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2, 0}
}

// AuthRequest represents the information that the caller requested
// authorization with.
type AuthRequest struct {
	RedirectUri          string                   `protobuf:"bytes,1,opt,name=redirect_uri,proto3" json:"redirect_uri,omitempty"`
	State                string                   `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	Scopes               []string                 `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Nonce                string                   `protobuf:"bytes,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ResponseType         AuthRequest_ResponseType `protobuf:"varint,5,opt,name=response_type,proto3,enum=oidc.core.v1beta1.AuthRequest_ResponseType" json:"response_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *AuthRequest) Reset()         { *m = AuthRequest{} }
func (m *AuthRequest) String() string { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()    {}
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *AuthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRequest.Unmarshal(m, b)
}
func (m *AuthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRequest.Marshal(b, m, deterministic)
}
func (m *AuthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRequest.Merge(m, src)
}
func (m *AuthRequest) XXX_Size() int {
	return xxx_messageInfo_AuthRequest.Size(m)
}
func (m *AuthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRequest proto.InternalMessageInfo

func (m *AuthRequest) GetRedirectUri() string {
	if m != nil {
		return m.RedirectUri
	}
	return ""
}

func (m *AuthRequest) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *AuthRequest) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *AuthRequest) GetNonce() string {
	if m != nil {
		return m.Nonce
	}
	return ""
}

func (m *AuthRequest) GetResponseType() AuthRequest_ResponseType {
	if m != nil {
		return m.ResponseType
	}
	return AuthRequest_UNKNOWN
}

// Authorization represents the information that the authentication process
// authorized the user for.
type Authorization struct {
	Scopes               []string             `protobuf:"bytes,1,rep,name=scopes,proto3" json:"scopes,omitempty"`
	Acr                  string               `protobuf:"bytes,2,opt,name=acr,proto3" json:"acr,omitempty"`
	Amr                  string               `protobuf:"bytes,3,opt,name=amr,proto3" json:"amr,omitempty"`
	AuthorizedAt         *timestamp.Timestamp `protobuf:"bytes,4,opt,name=authorized_at,proto3" json:"authorized_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Authorization) Reset()         { *m = Authorization{} }
func (m *Authorization) String() string { return proto.CompactTextString(m) }
func (*Authorization) ProtoMessage()    {}
func (*Authorization) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *Authorization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Authorization.Unmarshal(m, b)
}
func (m *Authorization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Authorization.Marshal(b, m, deterministic)
}
func (m *Authorization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Authorization.Merge(m, src)
}
func (m *Authorization) XXX_Size() int {
	return xxx_messageInfo_Authorization.Size(m)
}
func (m *Authorization) XXX_DiscardUnknown() {
	xxx_messageInfo_Authorization.DiscardUnknown(m)
}

var xxx_messageInfo_Authorization proto.InternalMessageInfo

func (m *Authorization) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *Authorization) GetAcr() string {
	if m != nil {
		return m.Acr
	}
	return ""
}

func (m *Authorization) GetAmr() string {
	if m != nil {
		return m.Amr
	}
	return ""
}

func (m *Authorization) GetAuthorizedAt() *timestamp.Timestamp {
	if m != nil {
		return m.AuthorizedAt
	}
	return nil
}

// Session represents an authenticated user from the time they are issued a
// code, until their last refresh/access token expires.
type Session struct {
	Id string `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	// stage represents where in the overall lifecycle this session is.
	Stage Session_Stage `protobuf:"varint,4,opt,name=stage,proto3,enum=oidc.core.v1beta1.Session_Stage" json:"stage,omitempty"`
	// request stores information about the original request we received.
	Request *AuthRequest `protobuf:"bytes,5,opt,name=request,proto3" json:"request,omitempty"`
	// tracks the details this session was actually authorized for
	Authorization *Authorization `protobuf:"bytes,6,opt,name=authorization,proto3" json:"authorization,omitempty"`
	// the client ID this session is bound to.
	ClientId string `protobuf:"bytes,7,opt,name=client_id,proto3" json:"client_id,omitempty"`
	// the scopes that have been granted for this session
	Scopes []string `protobuf:"bytes,8,rep,name=scopes,proto3" json:"scopes,omitempty"`
	// The authorization code that was issued for the code flow.
	AuthCode *StoredToken `protobuf:"bytes,9,opt,name=auth_code,proto3" json:"auth_code,omitempty"`
	// if the auth code has been previously redeemed. If we get a subsequent
	// redemption, we should drop the whole session
	//
	// https://tools.ietf.org/html/rfc6819#section-4.4.1.1
	AuthCodeRedeemed bool `protobuf:"varint,10,opt,name=auth_code_redeemed,proto3" json:"auth_code_redeemed,omitempty"`
	// The current access token, if one has been issued. It's expiration time
	// should always be checked.
	AccessToken *StoredToken `protobuf:"bytes,11,opt,name=access_token,proto3" json:"access_token,omitempty"`
	// The currently valid refresh token for this session. I
	RefreshToken *StoredToken `protobuf:"bytes,12,opt,name=refresh_token,proto3" json:"refresh_token,omitempty"`
	// The time the whole session should be expired at. It should be garbage
	// collected at this time.
	ExpiresAt            *timestamp.Timestamp `protobuf:"bytes,13,opt,name=expires_at,proto3" json:"expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Session) Reset()         { *m = Session{} }
func (m *Session) String() string { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()    {}
func (*Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{2}
}

func (m *Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Session.Unmarshal(m, b)
}
func (m *Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Session.Marshal(b, m, deterministic)
}
func (m *Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Session.Merge(m, src)
}
func (m *Session) XXX_Size() int {
	return xxx_messageInfo_Session.Size(m)
}
func (m *Session) XXX_DiscardUnknown() {
	xxx_messageInfo_Session.DiscardUnknown(m)
}

var xxx_messageInfo_Session proto.InternalMessageInfo

func (m *Session) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Session) GetStage() Session_Stage {
	if m != nil {
		return m.Stage
	}
	return Session_REQUESTED
}

func (m *Session) GetRequest() *AuthRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

func (m *Session) GetAuthorization() *Authorization {
	if m != nil {
		return m.Authorization
	}
	return nil
}

func (m *Session) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *Session) GetScopes() []string {
	if m != nil {
		return m.Scopes
	}
	return nil
}

func (m *Session) GetAuthCode() *StoredToken {
	if m != nil {
		return m.AuthCode
	}
	return nil
}

func (m *Session) GetAuthCodeRedeemed() bool {
	if m != nil {
		return m.AuthCodeRedeemed
	}
	return false
}

func (m *Session) GetAccessToken() *StoredToken {
	if m != nil {
		return m.AccessToken
	}
	return nil
}

func (m *Session) GetRefreshToken() *StoredToken {
	if m != nil {
		return m.RefreshToken
	}
	return nil
}

func (m *Session) GetExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

// StoredToken represents the session-persisted state of a token
// we issued to a user
type StoredToken struct {
	// bcrypted version of the token that was issued to the user
	Bcrypted []byte `protobuf:"bytes,1,opt,name=bcrypted,proto3" json:"bcrypted,omitempty"`
	// when this token expires
	ExpiresAt            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=expires_at,proto3" json:"expires_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *StoredToken) Reset()         { *m = StoredToken{} }
func (m *StoredToken) String() string { return proto.CompactTextString(m) }
func (*StoredToken) ProtoMessage()    {}
func (*StoredToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{3}
}

func (m *StoredToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoredToken.Unmarshal(m, b)
}
func (m *StoredToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoredToken.Marshal(b, m, deterministic)
}
func (m *StoredToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoredToken.Merge(m, src)
}
func (m *StoredToken) XXX_Size() int {
	return xxx_messageInfo_StoredToken.Size(m)
}
func (m *StoredToken) XXX_DiscardUnknown() {
	xxx_messageInfo_StoredToken.DiscardUnknown(m)
}

var xxx_messageInfo_StoredToken proto.InternalMessageInfo

func (m *StoredToken) GetBcrypted() []byte {
	if m != nil {
		return m.Bcrypted
	}
	return nil
}

func (m *StoredToken) GetExpiresAt() *timestamp.Timestamp {
	if m != nil {
		return m.ExpiresAt
	}
	return nil
}

// UserToken is the value we issue directly to users. The message is serialized,
// then base64 encoded to make up the issued version.
type UserToken struct {
	// the ID of the session this token corresponds to
	SessionId string `protobuf:"bytes,1,opt,name=session_id,proto3" json:"session_id,omitempty"`
	// the token itself, to be compared to the bcrypt version on the backend
	Token                []byte   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserToken) Reset()         { *m = UserToken{} }
func (m *UserToken) String() string { return proto.CompactTextString(m) }
func (*UserToken) ProtoMessage()    {}
func (*UserToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{4}
}

func (m *UserToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserToken.Unmarshal(m, b)
}
func (m *UserToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserToken.Marshal(b, m, deterministic)
}
func (m *UserToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserToken.Merge(m, src)
}
func (m *UserToken) XXX_Size() int {
	return xxx_messageInfo_UserToken.Size(m)
}
func (m *UserToken) XXX_DiscardUnknown() {
	xxx_messageInfo_UserToken.DiscardUnknown(m)
}

var xxx_messageInfo_UserToken proto.InternalMessageInfo

func (m *UserToken) GetSessionId() string {
	if m != nil {
		return m.SessionId
	}
	return ""
}

func (m *UserToken) GetToken() []byte {
	if m != nil {
		return m.Token
	}
	return nil
}

func init() {
	proto.RegisterEnum("oidc.core.v1beta1.AuthRequest_ResponseType", AuthRequest_ResponseType_name, AuthRequest_ResponseType_value)
	proto.RegisterEnum("oidc.core.v1beta1.Session_Stage", Session_Stage_name, Session_Stage_value)
	proto.RegisterType((*AuthRequest)(nil), "oidc.core.v1beta1.AuthRequest")
	proto.RegisterType((*Authorization)(nil), "oidc.core.v1beta1.Authorization")
	proto.RegisterType((*Session)(nil), "oidc.core.v1beta1.Session")
	proto.RegisterType((*StoredToken)(nil), "oidc.core.v1beta1.StoredToken")
	proto.RegisterType((*UserToken)(nil), "oidc.core.v1beta1.UserToken")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 645 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x6f, 0xd3, 0x4a,
	0x10, 0xbd, 0x76, 0x3e, 0x3d, 0x49, 0x7a, 0x7d, 0xf7, 0x5e, 0x5d, 0x4c, 0x84, 0x4a, 0xe4, 0xa7,
	0x48, 0x48, 0x2e, 0x0d, 0x12, 0x42, 0x88, 0x07, 0xd2, 0xc6, 0x15, 0xb4, 0x28, 0x55, 0xd7, 0x89,
	0x90, 0x78, 0xb1, 0x1c, 0x7b, 0x9a, 0x5a, 0x34, 0x5e, 0xb3, 0xbb, 0x01, 0xc2, 0x7f, 0xe0, 0x91,
	0x3f, 0xcb, 0x13, 0xf2, 0xda, 0x6d, 0xed, 0xd2, 0x42, 0x79, 0xf3, 0xcc, 0x9c, 0x73, 0x76, 0xe6,
	0xec, 0x78, 0xa1, 0x27, 0x24, 0xe3, 0xc1, 0x12, 0x9d, 0x94, 0x33, 0xc9, 0xc8, 0x3f, 0x2c, 0x8e,
	0x42, 0x27, 0x64, 0x1c, 0x9d, 0x8f, 0xbb, 0x0b, 0x94, 0xc1, 0x6e, 0xff, 0xe1, 0x92, 0xb1, 0xe5,
	0x39, 0xee, 0x28, 0xc0, 0x62, 0x7d, 0xba, 0x23, 0xe3, 0x15, 0x0a, 0x19, 0xac, 0xd2, 0x9c, 0xd3,
	0xdf, 0xbe, 0x0e, 0xf8, 0xc4, 0x83, 0x34, 0x45, 0x2e, 0x8a, 0xfa, 0xfd, 0xeb, 0xf5, 0x20, 0xd9,
	0xe4, 0x25, 0xfb, 0xbb, 0x06, 0x9d, 0xf1, 0x5a, 0x9e, 0x51, 0xfc, 0xb0, 0x46, 0x21, 0x89, 0x0d,
	0x5d, 0x8e, 0x51, 0xcc, 0x31, 0x94, 0xfe, 0x9a, 0xc7, 0x96, 0x36, 0xd0, 0x86, 0x06, 0xad, 0xe4,
	0xc8, 0x7f, 0xd0, 0x10, 0x32, 0x90, 0x68, 0xe9, 0xaa, 0x98, 0x07, 0xe4, 0x7f, 0x68, 0x8a, 0x90,
	0xa5, 0x28, 0xac, 0xda, 0xa0, 0x36, 0x34, 0x68, 0x11, 0x65, 0xe8, 0x84, 0x25, 0x21, 0x5a, 0xf5,
	0x1c, 0xad, 0x02, 0x72, 0x02, 0x3d, 0x8e, 0x22, 0x65, 0x89, 0x40, 0x5f, 0x6e, 0x52, 0xb4, 0x1a,
	0x03, 0x6d, 0xb8, 0x35, 0x7a, 0xe4, 0xfc, 0x34, 0xbe, 0x53, 0x6a, 0xcf, 0xa1, 0x05, 0x67, 0xb6,
	0x49, 0x91, 0x56, 0x15, 0xec, 0xc7, 0xd0, 0x2d, 0x97, 0x49, 0x07, 0x5a, 0xf3, 0xe9, 0xd1, 0xf4,
	0xf8, 0xed, 0xd4, 0xfc, 0x8b, 0xb4, 0xa1, 0xbe, 0x7f, 0x3c, 0x71, 0x4d, 0x8d, 0x18, 0xd0, 0x98,
	0x1d, 0x1f, 0xb9, 0x53, 0x53, 0xb7, 0xbf, 0x6a, 0xd0, 0xcb, 0xd4, 0x19, 0x8f, 0xbf, 0x04, 0x32,
	0x66, 0x49, 0x69, 0x08, 0xad, 0x32, 0x84, 0x09, 0xb5, 0x20, 0xe4, 0xc5, 0xc0, 0xd9, 0xa7, 0xca,
	0xac, 0xb8, 0x55, 0x2b, 0x32, 0x2b, 0x4e, 0x5e, 0x42, 0x2f, 0x28, 0xc4, 0x30, 0xf2, 0x03, 0xa9,
	0x06, 0xee, 0x8c, 0xfa, 0x4e, 0xee, 0xbe, 0x73, 0xe1, 0xbe, 0x33, 0xbb, 0xb8, 0x3e, 0x5a, 0x25,
	0xd8, 0xdf, 0x1a, 0xd0, 0xf2, 0x50, 0x88, 0xac, 0x93, 0x2d, 0xd0, 0xe3, 0xa8, 0x90, 0xd7, 0xe3,
	0x88, 0x3c, 0x55, 0xa6, 0x2f, 0x73, 0x1b, 0xb7, 0x46, 0x83, 0x1b, 0x8c, 0x2a, 0xa8, 0x8e, 0x97,
	0xe1, 0x68, 0x0e, 0x27, 0xcf, 0xa0, 0xc5, 0x73, 0xf3, 0x94, 0xc5, 0x9d, 0xd1, 0xf6, 0xaf, 0x2d,
	0xa6, 0x17, 0x70, 0x72, 0x70, 0x35, 0x8f, 0x32, 0xc7, 0x6a, 0x2a, 0xfe, 0xe0, 0x16, 0xfe, 0x25,
	0x8e, 0x56, 0x69, 0xe4, 0x01, 0x18, 0xe1, 0x79, 0x8c, 0x89, 0xf4, 0xe3, 0xc8, 0x6a, 0xa9, 0x81,
	0xae, 0x12, 0x25, 0xc7, 0xdb, 0x15, 0xc7, 0x5f, 0x80, 0x91, 0xc9, 0xf8, 0x21, 0x8b, 0xd0, 0x32,
	0x6e, 0xed, 0xdc, 0x93, 0x8c, 0x63, 0x34, 0x63, 0xef, 0x31, 0xa1, 0x57, 0x04, 0xe2, 0x00, 0xb9,
	0x0c, 0x7c, 0x8e, 0x11, 0xe2, 0x0a, 0x23, 0x0b, 0x06, 0xda, 0xb0, 0x4d, 0x6f, 0xa8, 0x90, 0x3d,
	0xe8, 0x06, 0x61, 0x88, 0x42, 0xf8, 0x32, 0x93, 0xb2, 0x3a, 0x77, 0x3a, 0xb0, 0xc2, 0x21, 0x93,
	0x6c, 0xa5, 0x4f, 0x39, 0x8a, 0xb3, 0x42, 0xa4, 0x7b, 0x27, 0x91, 0x2a, 0x89, 0x3c, 0x07, 0xc0,
	0xcf, 0x69, 0xcc, 0x51, 0x64, 0x2b, 0xd4, 0xfb, 0xed, 0x0a, 0x95, 0xd0, 0xf6, 0x21, 0x34, 0xd4,
	0xdd, 0x93, 0x1e, 0x18, 0xd4, 0x3d, 0x99, 0xbb, 0xde, 0xcc, 0x9d, 0x54, 0x96, 0xff, 0x1e, 0xfc,
	0x3b, 0xde, 0xdf, 0x77, 0x3d, 0xcf, 0x57, 0xff, 0x80, 0xff, 0xda, 0xf3, 0xe6, 0xee, 0xc4, 0xd4,
	0xc9, 0xdf, 0xd0, 0xa1, 0xee, 0x01, 0x75, 0xbd, 0x57, 0xe3, 0xbd, 0x37, 0xae, 0x59, 0x3b, 0xac,
	0xb7, 0x35, 0x53, 0x3f, 0xac, 0xb7, 0x75, 0xb3, 0x66, 0x23, 0x74, 0x4a, 0x1d, 0x93, 0x3e, 0xb4,
	0x17, 0x21, 0xdf, 0xa4, 0x12, 0x23, 0xf5, 0x3e, 0x74, 0xe9, 0x65, 0x7c, 0xad, 0x7d, 0xfd, 0x8f,
	0xda, 0x1f, 0x83, 0x31, 0x17, 0xc8, 0xf3, 0x43, 0xb6, 0x01, 0x44, 0xbe, 0xcf, 0xd9, 0xda, 0xe4,
	0xcf, 0x50, 0x29, 0x93, 0x3d, 0x2b, 0xb9, 0xcb, 0xba, 0xea, 0x20, 0x0f, 0xf6, 0x9a, 0xef, 0xea,
	0x99, 0xd1, 0x8b, 0xa6, 0x3a, 0xea, 0xc9, 0x8f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5e, 0x18, 0x26,
	0x6b, 0x5d, 0x05, 0x00, 0x00,
}
