// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storage.proto

package storage

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Keys hold encryption and signing keys.
type Keys struct {
	// Key for creating and verifying signatures. These may be nil. They are
	// store a JWK JSON Blobs
	SigningKey    []byte `protobuf:"bytes,1,opt,name=SigningKey,json=signing_key,proto3" json:"SigningKey,omitempty"`
	SigningKeyPub []byte `protobuf:"bytes,2,opt,name=SigningKeyPub,json=signing_key_pub,proto3" json:"SigningKeyPub,omitempty"`
	// Old signing keys which have been rotated but can still be used to validate
	// existing signatures.
	VerificationKeys []*VerificationKey `protobuf:"bytes,3,rep,name=verification_keys,proto3" json:"verification_keys,omitempty"`
	// The next time the signing key will rotate.
	//
	// For caching purposes, implementations MUST NOT update keys before this
	// time.
	NextRotation         *timestamp.Timestamp `protobuf:"bytes,4,opt,name=next_rotation,proto3" json:"next_rotation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Keys) Reset()         { *m = Keys{} }
func (m *Keys) String() string { return proto.CompactTextString(m) }
func (*Keys) ProtoMessage()    {}
func (*Keys) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{0}
}

func (m *Keys) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Keys.Unmarshal(m, b)
}
func (m *Keys) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Keys.Marshal(b, m, deterministic)
}
func (m *Keys) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Keys.Merge(m, src)
}
func (m *Keys) XXX_Size() int {
	return xxx_messageInfo_Keys.Size(m)
}
func (m *Keys) XXX_DiscardUnknown() {
	xxx_messageInfo_Keys.DiscardUnknown(m)
}

var xxx_messageInfo_Keys proto.InternalMessageInfo

func (m *Keys) GetSigningKey() []byte {
	if m != nil {
		return m.SigningKey
	}
	return nil
}

func (m *Keys) GetSigningKeyPub() []byte {
	if m != nil {
		return m.SigningKeyPub
	}
	return nil
}

func (m *Keys) GetVerificationKeys() []*VerificationKey {
	if m != nil {
		return m.VerificationKeys
	}
	return nil
}

func (m *Keys) GetNextRotation() *timestamp.Timestamp {
	if m != nil {
		return m.NextRotation
	}
	return nil
}

// VerificationKey is a rotated signing key which can still be used to verify
// signatures.
type VerificationKey struct {
	// Stored as JWK JSON blob
	PublicKey            []byte               `protobuf:"bytes,1,opt,name=public_key,proto3" json:"public_key,omitempty"`
	Expiry               *timestamp.Timestamp `protobuf:"bytes,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *VerificationKey) Reset()         { *m = VerificationKey{} }
func (m *VerificationKey) String() string { return proto.CompactTextString(m) }
func (*VerificationKey) ProtoMessage()    {}
func (*VerificationKey) Descriptor() ([]byte, []int) {
	return fileDescriptor_0d2c4ccf1453ffdb, []int{1}
}

func (m *VerificationKey) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VerificationKey.Unmarshal(m, b)
}
func (m *VerificationKey) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VerificationKey.Marshal(b, m, deterministic)
}
func (m *VerificationKey) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VerificationKey.Merge(m, src)
}
func (m *VerificationKey) XXX_Size() int {
	return xxx_messageInfo_VerificationKey.Size(m)
}
func (m *VerificationKey) XXX_DiscardUnknown() {
	xxx_messageInfo_VerificationKey.DiscardUnknown(m)
}

var xxx_messageInfo_VerificationKey proto.InternalMessageInfo

func (m *VerificationKey) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *VerificationKey) GetExpiry() *timestamp.Timestamp {
	if m != nil {
		return m.Expiry
	}
	return nil
}

func init() {
	proto.RegisterType((*Keys)(nil), "deci.storage.v1beta1.Keys")
	proto.RegisterType((*VerificationKey)(nil), "deci.storage.v1beta1.VerificationKey")
}

func init() { proto.RegisterFile("storage.proto", fileDescriptor_0d2c4ccf1453ffdb) }

var fileDescriptor_0d2c4ccf1453ffdb = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0x4f, 0x4b, 0xc3, 0x30,
	0x18, 0x87, 0xa9, 0x1b, 0x13, 0xdf, 0x59, 0x86, 0xc1, 0x43, 0xd9, 0xc1, 0x95, 0x81, 0xd2, 0x53,
	0xc6, 0xea, 0x17, 0x10, 0xaf, 0xbd, 0x48, 0x27, 0x1e, 0xbc, 0x94, 0xa6, 0xbe, 0x0b, 0xc1, 0xad,
	0x09, 0x49, 0x3a, 0x96, 0x2f, 0xec, 0xe7, 0x90, 0xa5, 0x2d, 0xd6, 0x3f, 0x78, 0x7d, 0x78, 0x5e,
	0x7e, 0xef, 0x03, 0xa1, 0xb1, 0x52, 0x97, 0x1c, 0xa9, 0xd2, 0xd2, 0x4a, 0x72, 0xfd, 0x86, 0x95,
	0xa0, 0x3d, 0x3b, 0xac, 0x19, 0xda, 0x72, 0x3d, 0x5f, 0x70, 0x29, 0xf9, 0x0e, 0x57, 0xde, 0x61,
	0xcd, 0x76, 0x65, 0xc5, 0x1e, 0x8d, 0x2d, 0xf7, 0xaa, 0x3d, 0x5b, 0x7e, 0x04, 0x30, 0xce, 0xd0,
	0x19, 0xb2, 0x00, 0xd8, 0x08, 0x5e, 0x8b, 0x9a, 0x67, 0xe8, 0xa2, 0x20, 0x0e, 0x92, 0xcb, 0x7c,
	0x6a, 0x5a, 0x52, 0xbc, 0xa3, 0x23, 0x77, 0x10, 0x7e, 0x09, 0x4f, 0x0d, 0x8b, 0xce, 0xbc, 0x33,
	0x1b, 0x38, 0x85, 0x6a, 0x18, 0xd9, 0xc0, 0xd5, 0x01, 0xb5, 0xd8, 0x8a, 0xaa, 0xb4, 0x42, 0xd6,
	0x27, 0x6e, 0xa2, 0x51, 0x3c, 0x4a, 0xa6, 0xe9, 0x2d, 0xfd, 0xeb, 0x49, 0xfa, 0x32, 0xd0, 0x33,
	0x74, 0xf9, 0xef, 0x7b, 0xf2, 0x00, 0x61, 0x8d, 0x47, 0x5b, 0x68, 0x69, 0x3d, 0x8d, 0xc6, 0x71,
	0x90, 0x4c, 0xd3, 0x39, 0x6d, 0xfb, 0x68, 0xdf, 0x47, 0x9f, 0xfb, 0xbe, 0xfc, 0xfb, 0xc1, 0x12,
	0x61, 0xf6, 0x63, 0x87, 0xdc, 0x00, 0xa8, 0x86, 0xed, 0x44, 0x75, 0xda, 0xe8, 0x92, 0x07, 0x84,
	0xa4, 0x30, 0xc1, 0xa3, 0x12, 0xda, 0xf9, 0xd4, 0xff, 0xd7, 0x3a, 0xf3, 0xf1, 0xe2, 0xf5, 0xbc,
	0xcb, 0x63, 0x13, 0xaf, 0xdd, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0xec, 0xc1, 0x0b, 0xa9, 0xa9,
	0x01, 0x00, 0x00,
}
